before_script:
  - apt update -qq

  - apt install -y git make
  # https://askubuntu.com/a/1013396
  - DEBIAN_FRONTEND=noninteractive apt install -y fsharp

stages:
  - buildAndInstall
  - compileScripts
  - test
  - package

buildAndInstall-1804:
  image: ubuntu:18.04
  stage: buildAndInstall
  script:
    - ./configure.sh
    - make
    - make install

buildAndInstall-2004:
  image: ubuntu:20.04
  stage: buildAndInstall
  script:
    - ./configure.sh
    - make
    - make install

compileScripts-1804:
  image: ubuntu:18.04
  stage: compileScripts
  script:
    - ./configure.sh && make install
    - ./ci-build.fsx

compileScripts-2004:
  image: ubuntu:20.04
  stage: compileScripts
  script:
    - ./configure.sh && make install
    - ./ci-build.fsx

test-1804:
  image: ubuntu:18.04
  stage: test
  script:
    - ./configure.sh && make install
    - ./test.fsx
    - ./testProcessConcurrency.fsx

test-2004:
  image: ubuntu:20.04
  stage: test
  script:
    - ./configure.sh && make install
    - ./test.fsx
    - ./testProcessConcurrency.fsx

package-1804:
  image: ubuntu:18.04
  stage: package
  script:
    - apt install -y snapcraft
    - ./snap_build.sh

  artifacts:
    paths:
      - fsx*.snap
    expire_in: 50days

package-2004:
  image: ubuntu:20.04
  stage: package
  script:
    - apt install -y sudo
    - ./install_snapcraft_dockerless.sh
    # finish installation of snapcraft
    - export SNAP=/snap/snapcraft/current
    - export SNAP_NAME=snapcraft
    - export SNAP_ARCH=amd64
    - export PATH="/snap/bin:$PATH"

    - /snap/bin/snapcraft --version

    - ./scripts/snap_build.sh

  artifacts:
    paths:
      - fsx*.snap
    expire_in: 50days
